config/routes.rb
Rails.application.routes.draw do
  resources :hearts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :profiles
  resources :posts do
    resources :comments, only: :create
  end

  match 'like', to: 'hearts#like', via: :post
  match 'unlike', to: 'hearts#unlike', via: :delete

  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'popular', to: 'posts#index'
  get 'active', to: 'posts#index'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :body, :user, :post
end

app/models/heart.rb
class Heart < ActiveRecord::Base
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text(65535)
#  tags       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  acts_as_taggable

  validates :title, presence: true,
                    length: { minimum: 5, maximum: 140 },
                    uniqueness: true
  validates :body, presence: true,
                    length: { minimum: 140 }
  validates :user, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :hearts, dependent: :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  after_create :set_avatar
  belongs_to :user

  COUNTRIES = [['Ukraine', 'Ukraine'], ['Russian', 'Russian'], ['USA', 'USA'], ['Japan', 'Japan'], ['China', 'China'], ['Kazakhstan', 'Kazakhstan'], ['Poland', 'Poland'], ['Korea', 'Korea'], ['Canada', 'Canada'], ['Mexico', 'Mexico']]
  SEX = [['Man', 'Man'], ['Woman', 'Woman']]

  private

  def set_avatar
    self.avatar = Gravatar.new("generic@example.com").image_url unless self.avatar
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :default_profile
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password

  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  validates :password, length: { minimum: 6 }
  validates_presence_of :name

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :hearts, dependent: :destroy
  has_one :profile

  def heart!(post)
    self.hearts.create!(post_id: post.id)
  end

  def unheart!(post)
    heart = self.hearts.find_by_post_id(post.id)
    heart.destroy!
  end

  def heart?(post)
    self.hearts.find_by_post_id(post.id)
  end

  private

  def default_profile
    self.create_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate, except: [:index, :show]

  def check_user
    redirect_to root_path if logged_in?
  end

  def authenticate
    redirect_to new_session_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def banner
    if current_user
      session[:banner] += 1
    end
  end

  helper_method [:current_user, :banner]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @post.updated_at = Time.now
    if @comment.save && @post.save
      redirect_to :back, notice: 'Comment has created'
    else
      redirect_to :back, alert: 'Comment hasn\'t created'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  respond_to :js

  def like
    @user = current_user
    @post = Post.find(params[:post_id])
    if @post.user != current_user
      @user.heart!(@post)
    end
  end

  def unlike
    @user = current_user
    @heart = @user.hearts.find_by_post_id(params[:post_id])
    @post = Post.find(params[:post_id])
    @heart.destroy!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: :update

  def index
    @posts = if params[:q]
               Post.where('body LIKE ? OR title LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
             elsif params[:tag]
               Post.tagged_with(params[:tag])
             elsif params[:query] == 'popular'
               Post.select { |p| p.hearts.count > 0 }
             elsif params[:query] == 'active'
               Post.select { |p| Time.now - p.updated_at < 84400 }
             else
               Post.order('posts.created_at DESC').all
             end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @post = current_user.posts.find_by(id: params[:id])
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: 'You do not have permission'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all - [current_user]
  end

  def show
    user = User.find(params[:id])
    @profile = user.profile
  end

  def edit
    user = User.find(params[:id])
    @profile = user.profile
  end

  def update
    user = User.find(params[:id])
    @profile = user.profile

    if @profile.update(profile_params)
      redirect_to profile_path
      flash[:notice] = 'Your profile successfully updated.'
    else
      render :edit
      flash[:error] = 'Something wrong'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :country, :birthday, :sex, :about, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]
  before_filter :check_user, except: :destroy

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      session[:banner] = 1
      flash[:notice] = "You loged in as #{current_user.email}"
      redirect_to root_path
    else
      flash.now[:danger] = 'Incorrect password or email'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]
  before_filter :check_user

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to root_path, notice: "User saved"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.slim
h5
  = image_tag comment.user.profile.avatar, size: '40'
  '
  = comment.user.name
h5
  = comment.body
h5
  strong
    '#{time_ago_in_words(comment.created_at)} ago
br

app/views/comments/_form.html.slim
= simple_form_for([@post, @post.comments.build], html: { class: 'form-horizontal' }) do |f|
  = f.input :body
  = f.button :submit, 'Create comment', class: 'btn btn-primary'

app/views/hearts/_button.html.slim
- if current_user && post.user != current_user
  - if current_user.heart?(post)
    = link_to unlike_path(post_id: post.id), remote: true, method: :delete
      span.glyphicon.glyphicon-heart-empty
  - else
    = link_to like_path(post_id: post.id), remote: true, method: :post
      span.glyphicon.glyphicon-heart

app/views/hearts/like.js.erb
$('div#<%= dom_id(@post) %>').html('<%= "Like " %> <%= j render partial: "button", locals: {post: @post} %> <%= @post.hearts.count %>')

app/views/hearts/unlike.js.erb
$('div#<%= dom_id(@post) %>').html('<%= "Like " %> <%= j render partial: "button", locals: {post: @post} %> <%= @post.hearts.count %>')

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Posts", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      div style="font-size: 18px"
        ul.nav.navbar-nav.pull-right
          == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li = link_to 'Popular', controller: "posts", query: "popular"
li = link_to 'Active', controller: "posts", query: "active"

- if current_user
  li = form_tag('/posts', class: "navbar-form navbar-left", method: 'get') do
    .row.input-group
      = text_field_tag :q, params[:q], placeholder: 'Search here...', class: 'form-control'
      span.input-group-btn
        = submit_tag "Find!", class: "btn btn-default"
  li
    = link_to profile_path(current_user.profile), class: "navbar-avatar-container"
      = image_tag(current_user.profile.avatar, class: "navbar-avatar img-circle img-responsive")
  li = link_to 'Log out', session_path(current_user), method: 'delete'
- else
  li = link_to 'Sign in', new_user_path
  li = link_to 'Log in', new_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Collage'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Collage'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body.container
    .banner data-count="#{banner}"
    header
      == render 'layouts/navigation'
    main[role="main"]
      == yield

app/views/posts/_form.html.slim
.row
  .col-md-6.col-md-offset-3
    = simple_form_for @post do |f|
      = f.input :title
      = f.input :body
      = f.input :tag_list
      = f.input :image
      = f.button :submit, class: "btn btn-primary"
      = link_to "Back to posts", posts_path, class: "btn btn-default"

app/views/posts/edit.html.slim
h1.text-center Edit post
= render 'form'

app/views/posts/index.html.slim
h1.text-center Posts
h3
  = link_to 'New post', new_post_path, class: "btn btn-primary"
- @posts.each do |post|
  .row
    .thumbnail
      .caption
        h3
          = image_tag(post.user.profile.avatar, size: '40')
          '
          = post.user.name
        h3
          = link_to post.title, post_path(post)
        - if post.image
          = image_tag(post.image, class: "index-image")
        h5
          = post.body
        h6
          = raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
        h5
          strong
            '#{time_ago_in_words(post.created_at)} ago

        - if post.user == current_user
          = link_to 'Edit', edit_post_path(post), class: "btn btn-default"
          = link_to 'Destroy', post_path(post), method: 'delete', data: {confirm: 'Are you sure?'}, class: "btn btn-danger"

        h4
          = div_for post do
            = "Like  "
            = render partial: "hearts/button", locals: { post: post }
            = " #{post.hearts.count}"

app/views/posts/new.html.slim
h1.text-center New post
= render 'form'

app/views/posts/show.html.slim
.row
  .thumbnail
    .caption
      h3
        = image_tag(@post.user.profile.avatar, size: '40')
        '
        = @post.user.name
      h3
        = @post.title
      - if @post.image
        = image_tag(@post.image, class: "show-image")
      h5
        = @post.body
      h6
        = @post.tag_list
      h5
        strong
          '#{time_ago_in_words(@post.created_at)} ago

      .btn-group
        = link_to 'Back to posts', posts_path, class: "btn btn-default"
        - if @post.user == current_user
          = link_to 'Edit post', edit_post_path(@post), class: "btn btn-info"
          = link_to 'Delete post', post_path(@post), method: 'delete', class: 'btn btn-danger'

h2 Comments
#comments
  = render @post.comments
  = render 'comments/form'

app/views/profiles/edit.html.slim
.row
  .col-md-6.col-md-offset-3
    = simple_form_for @profile do |f|
      = f.input :country, collection: Profile::COUNTRIES
      = f.input :birthday, as: :date, start_year: Date.today.year - 90,
                                      end_year: Date.today.year - 12,
                                      order: [:day, :month, :year]
      = f.input :sex, collection: Profile::SEX
      = f.input :about
      = f.input :avatar
      = f.button :submit, class: "btn btn-primary"
      = link_to "Back to users", profiles_path, class: "btn btn-default"

app/views/profiles/index.html.slim
= image_tag(current_user.profile.avatar, size: '40')
= link_to " #{current_user.name}", edit_profile_path(current_user)
- @users.each do |user|
  = image_tag(user.profile.avatar, size: '40')
  = link_to user.name, profile_path(user.profile)

app/views/profiles/show.html.slim
h5
  = @profile.country
h5
  = @profile.birthday
h5
  = @profile.sex
h5
  = @profile.about
h5
  = @profile.avatar

= link_to "Back", profiles_path, class: "btn btn-primary"

app/views/users/new.html.slim
h1.text-center Sign up
.row
  .col-md-6.col-md-offset-3
    = simple_form_for(@user, html: { class: 'form-horizontal' }) do |f|
      = f.input :name
      = f.input :email
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit, 'Create my account', class: 'btn btn-primary'